apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirochain-pvc
  namespace: mirochain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
